import { Project, Experience } from "./types";

export const PROJECTS: Project[] = [
  {
    id: "veerla",
    title: "Veerla",
    technologies: ["SwiftUI", "SwiftData", "TMDB API", "CloudKit"],
    tags: ["Swift", "SwiftUI", "SwiftData"],
    link: "https://apps.apple.com/us/app/veerla-guard%C3%A1-pelis-y-series/id6744546242",
    type: "iOS",
  },
  {
    id: "cuenta-clara",
    title: "Cuenta Clara",
    technologies: ["Flutter", "Firebase Auth", "Firestore", "Provider"],
    tags: ["Dart", "Flutter", "Firebase"],
    link: "https://apps.apple.com/ni/app/cuenta-clara/id6743010799?l=en-GB",
    type: "Cross-platform",
  },
  {
    id: "todo-anotadito",
    title: "Todo Anotadito",
    technologies: ["SwiftUI", "SwiftData", "WidgetsKit", "App Intents"],
    tags: ["Swift", "SwiftUI", "SwiftData"],
    link: "https://todoanotadito.donmanuel.dev/",
    type: "iOS",
  },
  {
    id: "notyapp",
    title: "NotyApp",
    technologies: [
      "Kotlin",
      "Jetpack Compose",
      "Room Database",
      "Hilt",
      "Firebase",
    ],
    tags: ["Kotlin", "Firebase", "Room"],
    link: "https://play.google.com/store/apps/details?id=com.manuelduarte077.notyapp",
    type: "Android",
  },
  {
    id: "tucambio",
    title: "TuCambio",
    technologies: ["SwiftUI", "API Integration", "Charts"],
    tags: ["Swift", "SwiftUI", "Finance"],
    link: "https://apps.apple.com/ni/app/tucambio/id6744262206?l=en-GB",
    type: "iOS",
  },
];

export const EXPERIENCES: Experience[] = [
  {
    id: "software-engineer-ii",
    company: "Novacomp",
    position: "Software Engineer II",
    period: "Sep 2024 - Present",
    technologies: ["Java", "Objective-C", "C#", ".NET", "SQLServer", "Azure"],
    location: "remote",
    type: "full-time",
  },
  {
    id: "mobile-developer",
    company: "Socialenials",
    position: "Mobile Developer",
    period: "Sep 2023 - Feb 2026",
    technologies: ["Dart", "Flutter", "Firebase", "BloC", "PixelPay"],
    location: "remote",
    type: "part-time",
  },
  {
    id: "mobile-developer-flutter",
    company: "Disruptive Studio, Inc",
    position: "Mobile Developer",
    period: "June 2024 - Sep 2024",
    technologies: ["Dart", "Flutter", "Wallet", "BloC", "Crypto", "Blockchain"],
    location: "remote",
    type: "full-time",
  },
  {
    id: "software-engineer",
    company: "Nerdify",
    position: "Software Engineer",
    period: "Feb 2022 - Jun 2024",
    technologies: [
      "Dart",
      "Flutter",
      "BloC",
      "OneSignal",
      "Firebase",
      "GraphQL",
      "React Native",
      "Expo",
      "React",
    ],
    location: "on-site",
    type: "full-time",
  },
];
